joshjohanning/github-misc-scripts

- gh-cli/get-repos-using-actions.sh
The pagination was broken since `pageInfo` is missing
Made org name an parameter instead of being hardcoded
> Fix pagination and make org a parameter

- gh-cli/add-team-to-repository.sh
Add parameters to add-team-to-repository.sh script
The sample had hardcoded values, now everything is a parameter:
- Org
- Repo
- Team Slug
- Permission
> Parameterize add team repository

- gh-cli/README.md
- gh-cli/get-repositories-webhooks-csv.sh
Add `get-repositories-webhooks-csv.sh` script
Gets a CSV with the list of repository webhooks in a GitHub organization.
Generates a CSV with 4 columns:
- repo name - The repository name
- is active - If the webhook is active or not
- webhook url - The url of the weehook
- secret - Webhook secret, it will be masked since the API doesn't return the actual secret.
This script is useful when doing migrations, to determine the kind of actions that might be needed based on the webhooks inventory.
> Add script to get list of repo webhooks in a given org

- gh-cli/README.md
- gh-cli/get-enterprise-organizations.sh
enterprise slug is no longer hardcoded and can now be passed as a parameter
> Parameterize get-enterprise-organizations

- gh-cli/get-apps-installed-in-organization.sh
The org name is no longer hardcoded
> Parameterize get-apps-installed-in-organization

- gh-cli/README.md
- gh-cli/add-collaborator-to-repository.sh
- gh-cli/add-team-to-repository.sh
- gh-cli/copy-permissions-between-org-repos.sh
Copies user and teams membership between different repos (same or different org)
If the team doesn't exist create it (note: Doesn't recreate all team attributes)
> Add copy-permissions-between-org-repos script

- gh-cli/README.md
- gh-cli/copy-organization-team-members.sh
- gh-cli/copy-team-members.sh
`copy-team-members.sh` copies user members from one organization to the other. It only copies members doesn't delete existing members at target org.
`copy-organization-team-members.sh` Copies members from all teams that exist on the target org and also exist at the source. It calls `copy-team-members.sh` to do the actual copy, so same semantics apply.
> Add copy-organization-team-members.sh and copy-team-members.sh

- gh-cli/README.md
- gh-cli/get-app-tokens-for-each-installation.sh
Generates a JWT for a GitHub app and use that JWT to generate installation tokens for each org installation. The installation tokens, returned as `ghs_abc`, can then be used for normal API calls. It requires the App ID and Private Key `pem` file as input.
Notes:
- Not using `gh-cli` since we have to pass in JWT using `curl` (but otherwise no PAT required)
- Similar script to [get-apps-installed-in-organization.sh](./../scripts/get-app-tokens-for-each-installation.sh), but this one doesn't have a python dependency
> adding shell example for github app token generation

- gh-cli/README.md
- gh-cli/get-workflow-dispatch-inputs.sh
Gets a list of `workflow_dispatch` inputs used to queue a workflow run since it's not available otherwise in the API
Example output:
```json
[
{
"workflowName": "workflow-b",
"workflowId": "5870059990",
"inputs": {
"animal": "bee",
"color": "orange",
"food": "avocado"
},
"createdAt": "2023-08-15T17:45:21Z",
"conclusion": "success"
}
],
```
> adding script to retrieve inputs from workflow_dispatch triggered workflow runs

- gh-cli/README.md
- gh-cli/set-org-ip-allow-list-rules.sh
Sets the IP allow list rules for an organization from a set of rules defined in a file, based on the rules file the script sets, updates or deletes IP allow list rules 
The script is idempotent running it multiple times will only make the changes needed to match the rules in the file.
In order to insure availability of the service, the script first adds all necessary rules and only after that will delete rules no longer applicable, this insures no disruption of service if the change has an (partial) overlapping set of rules.
Optionally you can opt-in in to save a backup of rules on GitHub before the changes are applied.
> Add set-org-ip-allow-list-rules.sh

- gh-cli/README.md
- gh-cli/set-ip-allow-list-rules.sh
cc @tspascoal - slightly more involved than I thought since GraphQL for _getting_ IP allow lists between org and enterprise is different.  Setting/removing is the same, though. 
What do you think? 
Seems to work though! 
```
./set-ip-allow-list-rules.sh --enterprise my-enterprise --rules-file ip-allow-rules.json --dry-run
Running in dry-run mode. No changes will be made
Current number of rules in my-enterprise: 5
Number of rules in ip-allow-rules.json: 3
Checking new or updated rules to add
Adding rule: proxy-eu with value: 192.168.88.0/23
Adding rule: proxy-us with value: 192.168.1.1
Adding rule: proxy-us with value: 192.168.1.2
Checking rules no longer relevant for deletion
Deleting rule:  with value: 1.2.3.4 with id: IALE_kwDNCRTOAA1Hew
Deleting rule: josh with value: 1.2.3.5 with id: …
```
> Updating IP allow list script to support enterprises

- gh-cli/README.md
- gh-cli/get-actions-usage-in-organization.sh
- gh-cli/get-actions-usage-in-repository.sh
Returns a list of all actions used in an organization using the SBOM API
Example output:
```csv
71 actions/checkout@3
42 actions/checkout@2
13 actions/upload-artifact@2
13 actions/setup-node@3
```
Or (`count-by-action` option to count by action as opposed to action@version):
```csv
130 actions/checkout
35 actions/upload-artifact
27 actions/github-script
21 actions/setup-node
```
> **Note**
> The count returned is the # of repositories that use the action - if single a repository uses the action 2x times, it will only be counted 1x
> Adding actions usage by org script

- gh-cli/copy-organization-team-members.sh
Pagination for getting teams list in copy-organization-team-members was not being paginated. 
Only first 30 teams were being copied.
> Fix: Copy organization team members only copied first 30 teams

- gh-cli/delete-packages-in-organization.sh
- scripts/migrate-maven-packages-between-github-instances.sh
- scripts/migrate-npm-packages-between-github-instances.sh
- scripts/migrate-nuget-packages-between-github-instances.sh
- maven package migration script: 
- change logic `mvnfeed-cli` is installed
- use `GH_TOKEN=$GH_SOURCE_PAT` for only authenticating a single `gh api` call
- removing unneeded api call to retrieve current user for source/target
- updating notes
- npm package migration script: 
- use `GH_TOKEN=$GH_SOURCE_PAT` for only authenticating a single `gh api` call
- updating notes
- nuget package migration script:
- updating notes
- delete packages script: 
- retrieving packages before sleep in order to error out sooner
> Update package migration scripts

- gh-cli/README.md
- gh-cli/parent-organization-teams.sh
Mirrors the parent/child relationship for teams on a target organization, based on the relations in the (teams) source org.
It doesn't create any teams, it just mirrors the parent of a team.
> Parent child/parent relations on org teams

- gh-cli/README.md
- gh-cli/get-organization-codeowner-errors-tsv.sh
Gets a TSV with the list of errors in codeowners file
repositories with no CODEOWNER files or with no errors will not be show
The list will contain the repository name, source (CODEOWNERS file), and kind of error.
> Get a list of CODEOWNERS with errors on a given org

- gh-cli/README.md
- gh-cli/__copy_team_and_children_if_not_exists_at_target.sh
- gh-cli/copy-permissions-between-org-repos.sh
- gh-cli/internal/__copy_team_and_children_if_not_exists_at_target.sh
When a team is copied from source to target, previously it was ensured the team existed at the target by copying it. Now it also ensures all children teams of copied teams are also at the target (creates them if necessary).
> copy permissions between org repos now also creates the child teams

- scripts/migrate-npm-packages-between-github-instances.sh
Failed for me without registry key.
See format here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#publishing-a-package-using-a-local-npmrc-file
> set 'registry=<host>' in .npmrc to allow auth

- gh-cli/README.md
- gh-cli/set-branch-protection-status-checks.sh
- Using the "[Update status check protection](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-status-check-protection)" API instead of the (deprecated?) "[Set status check contexts](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#set-status-check-contexts)" API
- This allows us to set the App ID - GitHub Actions (`15368`), GitHub Advanced Security (`57789`), or Azure Pipelines (`9426`) - for the  status checks for best security
> feat: improve status checks script

- gh-cli/README.md
- gh-cli/remove-branch-protection-status-check-contexts.sh
- gh-cli/remove-branch-protection-status-checks.sh
- gh-cli/set-branch-protection-status-checks.sh
- breaking change: adding/renaming `remove-branch-protection-status-checks.sh` to `remove-branch-protection-status-check-contexts.sh`
- breaking change: using `remove-branch-protection-status-checks.sh` to remove ALL branch protection status checks (unsets the setting)
- improving `set-branch-protection-status-checks.sh` to also create a branch protection rule if it doesn't exist, and if a rule already does exist, ensure that the required status checks setting is set
> feat!: improving status check scripts

- scripts/migrate-maven-packages-between-github-instances.sh
> the mvnfeed-cli codebase for transferring maven packages has gotten a bit out of date. Turns out it fails for GitHub to GitHub. Based on an open issue, I have a patch that MIGHT work https://github.com/microsoft/mvnfeed-cli/compare/master...kenmuse:mvnfeed-cli:kenmuse/gh?expand=1
>  it downloads the files (and they seem to be valid), but when uploading it appears to put a content-disposition MIME separator into the payload. That wrecks the `pom.xml` and the `JAR` file. It's a sloppy fix, but seemed to resolve the issue. Not sure if it breaks everything else. Took a bit to set it up since some of the code it references was deprecated (so it pulls newer dependencies that are not compatible as-is)
Thanks @kenmuse for the fix!
> fix: mavenfeed-cli pkg was broken

- gh-cli/get-sso-credential-authorizations.sh
- gh-cli/get-sso-enabled-pats.sh
- gh-cli/get-sso-enabled-ssh-keys.sh
Updates to API references and credential types:
* [`gh-cli/get-sso-credential-authorizations.sh`](diffhunk://#diff-04b58c65b600bfe497e78fafcf328022703c6b672adfaa2e037c4025423f2f32R6-R13): Added a new API reference and expanded the list of credential types to include "OAuth app token" and "GitHub app token". Also, the `gh api` command was modified to improve the output format.
* [`gh-cli/get-sso-enabled-pats.sh`](diffhunk://#diff-1ffb237438fa1ed82f313abb13d3c120ba224fe5832d1b7a0793646f757e31c2R6-R15): Added a new API reference and expanded the list of credential types to include "OAuth app token" and "GitHub app token". The `gh api` command was also modified to improve the output format and to only get active PATs.
* [`gh-cli/get-sso-enabled-ssh-keys.sh`](diffhunk://#diff-24e53baa00e59bc474 …
> feat: enhance sso creds scripts and use json outputs by default

- gh-cli/README.md
- gh-cli/get-organization-webhooks.sh
- gh-cli/get-organizations-webhooks-in-enterprise.sh
Here are the key changes:
* [`gh-cli/get-organization-webhooks.sh`](diffhunk://#diff-b4708d4c6dd746290641f8787172436cbb7d764574743569c5cc2c2e0e5c73f6R1-R36): This script retrieves webhook information for a specified GitHub organization. It checks for proper usage and valid authentication, makes an API call to GitHub to fetch the webhook data, and formats the data as a TSV or JSON object based on user input.
* [`gh-cli/get-organizations-webhooks-in-enterprise.sh`](diffhunk://#diff-dc033a540ce285cedb42e3b00a7f4c07f3202f03e99ba9fc2bf519986432960dR1-R54): This script retrieves webhook information for all organizations within a specified GitHub enterprise. It checks for proper usage and valid authentication, makes API calls to GitHub to fetch the webhook data for each organization, and formats …
> feat: add scripts for retrieving organization webhooks

- gh-cli/README.md
- gh-cli/get-organization-webhooks.sh
- gh-cli/get-organizations-apps-count.sh
- gh-cli/get-organizations-codeowner-usage.sh
- gh-cli/get-organizations-custom-repository-roles-count.sh
- gh-cli/get-organizations-discussions-count.sh
- gh-cli/get-organizations-projects-count-classic.sh
- gh-cli/get-organizations-projects-count.sh
- gh-cli/get-organizations-webhooks.sh
Addition of new script:
* [`gh-cli/get-organizations-custom-repository-roles-count.sh`](diffhunk://#diff-429ccba8187ba4dcaf78835e6bfaeceaa5cb59351478ddb2fb856dcebd01b433R1-R46): A new script was added that gets the count of custom repository roles in all organizations in a given enterprise. The script includes necessary authentication and usage instructions.
Modifications to output format notes:
* [`gh-cli/get-organization-webhooks.sh`](diffhunk://#diff-b4708d4c6dd746290641f8787172436cbb7d764574743569c5cc2c2e0e5c73f6R8-R10): Added notes about the output format, specifying that tsv is the default format and provides a subset of fields, while json provides all fields. [[1]](diffhunk://#diff-b4708d4c6dd746290641f8787172436cbb7d764574743569c5cc2c2e0e5c73f6R8-R10) …
> Add organizations custom repository roles count script

- gh-cli/get-enterprise-organizations.sh
- gh-cli/get-organizations-apps-count.sh
- gh-cli/get-organizations-apps.sh
- gh-cli/get-organizations-codeowner-usage.sh
- gh-cli/get-organizations-custom-repository-roles-count.sh
- gh-cli/get-organizations-discussions-count.sh
- gh-cli/get-organizations-settings.sh
- gh-cli/get-organizations-webhooks.sh
Error handling improvements:
* Added null checks and user-friendly error messages for missing organizations in `gh-cli/get-enterprise-organizations.sh`, `gh-cli/get-organizations-apps-count.sh`, `gh-cli/get-organizations-apps.sh`, `gh-cli/get-organizations-codeowner-usage.sh`, `gh-cli/get-organizations-custom-repository-roles-count.sh`, `gh-cli/get-organizations-discussions-count.sh`, `gh-cli/get-organizations-settings.sh`, and `gh-cli/get-organizations-webhooks.sh`. [[1]](diffhunk://#diff-700865b86638b6b1fd60c2a15edaa7a47d90005e4e566547c8592d8c8631772dL24-R43) [[2]](diffhunk://#diff-b8ce3c9301023228950121eb0d831cbbd9c16835c8e882fcceff9ecf462fb106R41-R53) [[3]](diffhunk://#diff-99f71b29faa25c1a438ca43c49081e0ec6ce2a93908ec56d68bea35a0cc95421R48-R60) …
> feat: improve error handling when querying enterprise orgs

- gh-cli/README.md
- gh-cli/add-all-organization-members-to-a-team.sh
Adds a script to add all organization members to a team.
> feat: add script to add all organization members to a team

- gh-cli/README.md
- gh-cli/add-sub-issue-to-issue.sh
- gh-cli/remove-issue-issue-type.sh
- gh-cli/remove-sub-issue-from-issue.sh
- gh-cli/update-issue-issue-type.sh
* [`gh-cli/add-sub-issue-to-issue.sh`](diffhunk://#diff-db5b46365c6237cf328e8e31991edd341067b7aa3c72e9bc3bdcea410954d3e7R1-R79): Adds a sub-issue (child) to an issue (parent).
* [`gh-cli/remove-issue-issue-type.sh`](diffhunk://#diff-1e5c2d6b48e9daaf666a9204702d36ee2456099ce6f96b4c27c9e520f3451cd1R1-R68): Removes the issue type from an issue (sets it to `null`).
* [`gh-cli/remove-sub-issue-from-issue.sh`](diffhunk://#diff-df13df31631a713aa93fe76935a0393ca997cf3a1287860988b23f0791518727R1-R101): Removes a sub-issue (child) from an issue (parent).
* [`gh-cli/update-issue-issue-type.sh`](diffhunk://#diff-0eeace169bda23ef7839e0d5e1c34d4443949d9c9efcf2292a01257ba7b3372fR1-R76): Updates or sets the issue type for an issue.
* [`gh-cli/README.md`](diffhunk://#diff-9ec2a7e2e655724844893270790b168184 …
> feat: adding issue types / sub-issues scripts

- gh-cli/README.md
- gh-cli/add-sub-issue-to-issue.sh
- gh-cli/get-parent-issue-of-issue.sh
- gh-cli/get-sub-issue-summary-of-issue.sh
- gh-cli/get-sub-issues-of-issue.sh
- gh-cli/remove-sub-issue-from-issue.sh
* [`gh-cli/get-parent-issue-of-issue.sh`](diffhunk://#diff-63178b14a029894e97ab7f903706b3e541609f791594c736f2358e44f7f267a7R1-R68): Added a new script to fetch the parent issue of a given sub-issue (child).
* [`gh-cli/get-sub-issue-summary-of-issue.sh`](diffhunk://#diff-4a0cd834b76bbd47d801fe0d690b975408cd13cd5e3378c10f5c1ec7aed2a4d0R1-R71): Added a new script to get a summary of the sub-issues (children) of an issue (parent).
* [`gh-cli/get-sub-issues-of-issue.sh`](diffhunk://#diff-dcd85b01f336539366c12a0c3e62321aa1abf7b9aeff372a63f7636ed2dffbf2R1-R73): Added a new script to retrieve a list of sub-issues from an issue.
* [`gh-cli/README.md`](diffhunk://#diff-9ec2a7e2e655724844893270790b168184c962e7b1ac9fe5dd0c32783cff7fd1R915-R918): Updated the documentation to include new sections for …
> Add sub issue and parent scripts

- gh-cli/README.md
- gh-cli/add-sub-issue-to-issue.sh
- gh-cli/get-issue-type-of-issue.sh
- gh-cli/get-parent-issue-of-issue.sh
- gh-cli/get-sub-issues-of-issue.sh
- gh-cli/remove-issue-issue-type.sh
- gh-cli/remove-sub-issue-from-issue.sh
- gh-cli/update-issue-issue-type.sh
* Added the `id` field to multiple GraphQL queries to ensure the issue ID is retrieved along with other issue details. [[1]](diffhunk://#diff-db5b46365c6237cf328e8e31991edd341067b7aa3c72e9bc3bdcea410954d3e7R58) [[2]](diffhunk://#diff-db5b46365c6237cf328e8e31991edd341067b7aa3c72e9bc3bdcea410954d3e7R67) [[3]](diffhunk://#diff-63178b14a029894e97ab7f903706b3e541609f791594c736f2358e44f7f267a7R45) [[4]](diffhunk://#diff-63178b14a029894e97ab7f903706b3e541609f791594c736f2358e44f7f267a7L64-R77) [[5]](diffhunk://#diff-dcd85b01f336539366c12a0c3e62321aa1abf7b9aeff372a63f7636ed2dffbf2R47) [[6]](diffhunk://#diff-dcd85b01f336539366c12a0c3e62321aa1abf7b9aeff372a63f7636ed2dffbf2L69-R81) [[7]](diffhunk://#diff-1e5c2d6b48e9daaf666a9204702d36ee2456099ce6f96b4c27c9e520f3451cd1R55) …
> Add script to get issue type of an issue

- gh-cli/README.md
- gh-cli/get-sub-issues-summary-of-issue.sh
Changes to script names and documentation:
* [`gh-cli/README.md`](diffhunk://#diff-9ec2a7e2e655724844893270790b168184c962e7b1ac9fe5dd0c32783cff7fd1L1099-R1106): Removed the entry for `get-sub-issue-summary-of-issue.sh` and added an entry for `get-sub-issues-summary-of-issue.sh` to correct the script name and description.
* [`gh-cli/get-sub-issues-summary-of-issue.sh`](diffhunk://#diff-f8f1698f55cf7e846e22d77204b7aa186f6ae1c5dc1ff265508ed0d90d5e8a67L3-R7): Renamed the script from `get-sub-issue-summary-of-issue.sh` to `get-sub-issues-summary-of-issue.sh` and updated the usage example in the script comments to reflect the new name.
> refactor!: rename get-sub-issue-summary-of-issue.sh to get-sub-issues-summary-of-issue.sh

- gh-cli/README.md
- gh-cli/invite-users-to-org-from-list.sh
- gh-cli/invite-users-to-organization-from-list.sh
Add a scripts to invite users to an org.
Useful for larger orgs or those in education.
Thoughts:
1. Is the file naming okay / consistent enough?
2. Invitations are based on email, which is different from other scripts where the user CSV expects usernames
Thanks for the project!
Was helpful to me :)
> Invite users to org

- git/README.md
- git/git-commit-analyzer.sh
- git/git-repo-commit-analyzer.sh
This pull request introduces two new bash scripts to analyze Git commit sizes. The first script analyzes the size of a specific commit, while the second script analyzes all commits in a repository and generates detailed logs and reports.
- **git-commit-analyzer.sh**: This script takes a commit hash as an argument and analyzes the size of that specific commit.
- **git-repo-commit-analyzer.sh**: This script analyzes all commits in a repository and generates detailed logs and reports, including:
- A CSV list of all commits, their sizes, and number of files in the commit
- A report of all commits over a certain size, including files, files sizes, and total commit size
- Updated README.md
> Git scripts: checks commit sizes for entire repo and specific hash

- gh-cli/README.md
- gh-cli/add-collaborator-to-repository.sh
- gh-cli/add-user-to-project.sh
- gh-cli/invite-user-to-repository.sh
BREAKING CHANGE: Parameter order changed in add-collaborator-to-repository.sh and add-user-to-project.sh
- BREAKING: Change parameter order in add-collaborator-to-repository.sh (role before login)
- BREAKING: Change parameter order in add-user-to-project.sh (role before user)
- Add comprehensive error handling to add-user-to-project.sh for API failures
- Add invite-user-to-repository.sh wrapper script for better discoverability
> refactor!: standardize parameter order for invite/add scripts and rove error handling

- gh-cli/get-most-recent-migration-id-for-repository.sh
- gh-cli/unlock-repository-migration-by-id.sh
- gh-cli/unlock-repository-migration.sh
Adds error handling to give more information on why the script may have failed; whether it be OAuth CLI token instead of classic PAT, migration doesn't exist, or not enough permissions.
> feat: enhance migration scripts with detailed error handling and usage instructions

- gh-cli/get-sso-credential-authorizations.sh
- gh-cli/get-sso-enabled-pats.sh
- gh-cli/get-sso-enabled-ssh-keys.sh
parameterize the `./get-sso-*` scripts.
> feat: add usage instructions for organization parameter in SSO credential scripts

- gh-cli/README.md
- gh-cli/add-team-to-repository.sh
- gh-cli/add-user-to-repository.sh
- gh-cli/invite-user-to-repository.sh
* `add-user-to-repository.sh` now checks for and cancels any existing expired invitations for a user before adding them (unless `skip_invite_check` is set to true)
* `invite-user-to-repository.sh` now calls `add-user-to-repository.sh` instead of the old `add-collaborator-to-repository.sh`, reflecting the script renaming and clarifying its purpose.
> feat: update add-user-to-repository script to include existing invitation check

- gh-cli/README.md
- gh-cli/enable-secret-scanning-on-repositories.sh
* Added `enable-secret-scanning-on-repositories.sh`, a script that enables secret scanning and related features (push protection, AI detection, non-provider patterns, validity checks) on all repositories in an organization or from a file list. Supports both public and private repositories, with logic to handle Advanced Security requirements for private repos. Includes dry-run mode, structured feature selection, detailed status reporting, and error handling.
> feat: add script to enable secret scanning on repositories script

- .github/copilot-instructions.md
- .github/prompts/add-script-to-readme.prompt.md
Adding Copilot instructions and prompt (`/add-script-to-readme` in VS Code).
> feat: add copilot instructions and prompt for adding new scripts to README.md

- gh-cli/README.md
- gh-cli/get-project-board-items.sh
* Added `get-project-board-items.sh`, a script that retrieves and formats all items from a GitHub Projects V2 board, including issues, pull requests, draft issues, custom field values, and labels. The script uses GitHub's GraphQL API.
> feat: add script to extract items from  Projects V2 board

- gh-cli/README.md
- gh-cli/get-actions-usage-in-organization.sh
- gh-cli/get-actions-usage-in-repository.sh
**Improvements to script functionality and flexibility:**
* Added support for `--resolve-shas` and `--dedupe-by-repo` flags in `get-actions-usage-in-organization.sh`, allowing users to resolve commit SHAs to tags and count unique repositories per action, respectively. Input validation ensures these flags are only used with the appropriate counting modes. [[1]](diffhunk://#diff-f8d9fcbfdd9e9ac6a71bbfa113bd99fc9e17ba0eaa4fe627bbdd6c8296a5c04cL6-R37) [[2]](diffhunk://#diff-f8d9fcbfdd9e9ac6a71bbfa113bd99fc9e17ba0eaa4fe627bbdd6c8296a5c04cR47-R128)
* Implemented caching for SHA-to-tag resolution in `get-actions-usage-in-organization.sh` to improve performance and avoid redundant API calls. Temporary files are cleaned up automatically.
* Enhanced counting logic to support deduplication by …
> feat: major enhancements to actions usage scripts

- gh-cli/get-project-board-items.sh
**Comment and metadata enhancements:**
* Added GraphQL queries to fetch up to 100 comments for both issues and pull requests, including author, creation, and update timestamps.
**General improvements:**
* Improved label output for issues by trimming trailing whitespace for cleaner display.
> feat: add comments retrieval for issues and pull requests in project board script

- gh-cli/README.md
- gh-cli/get-migration-status.sh
* Added `get-migration-status.sh` script to the `gh-cli` directory, which fetches migration details (ID, source URL, migration source, state, and failure reason) for a given GraphQL migration ID using the GitHub CLI and GraphQL API.
> feat: add script to retrieve migration status using GraphQL

- gh-cli/README.md
- gh-cli/get-actions-repository-variables-in-organization.sh
* Added `get-actions-repository-variables-in-organization.sh` script to export all Actions repository variables and their values from every repository in a specified organization to a CSV file.
> feat: add script to export repository variables from repositories in an organization

- .github/copilot-instructions.md
**Script guidelines and best practices:**
* Expanded requirements for scripts in both `gh-cli` and `scripts` directories, including input validation, meaningful error messages, use of pagination, preference for `--jq` in `gh api` commands, inclusion of specific GraphQL headers, and folder organization for complex scripts.
* Added instructions to keep descriptions concise, avoid periods in bullet points, and updated section headings for clarity.
* Added requirement to support custom hostnames for GitHub Enterprise instances in scripts when relevant.
**Commit message guidelines:**
* Introduced a new section detailing the Conventional Commits specification, including recommended types, scopes, formatting, and how to indicate breaking changes.
> docs: update copilot instructions
