gh-cli/get-enterprise-members.sh
gh-cli/get-enterprise-owners.sh

Recent customer request that I could not find on the samples.
Maybe is useful to have this sample in the repo too.

feat: get-enterprise-owners

---

gh-cli/README.md
gh-cli/copy-organization-members.sh

for EMU the users are added
for GHEC users are invited

Add script to copy members from one organization to the other

---

gh-cli/README.md
gh-cli/get-organizations-projects-count.sh

Counts the number of projects in all organization in a given enterprise

Add get-organizations-projects-count.sh

---

gh-cli/README.md
gh-cli/delete-repository-webhooks.sh

Delete all webhooks from a given repository

Add delete-repository-webhooks.sh

---

gh-cli/README.md
gh-cli/copy-repository-environments.sh

Copy environments from one (org) repo to another

Add copy-repository-environments.sh

---

gh-cli/README.md
gh-cli/get-repositories-autolinks-csv.sh

Generates a CSV with repositories autolinks in a given organization

Get org repositories autolinks

---

gh-cli/get-enterprise-ip-allow-list.sh
gh-cli/get-organization-ip-allow-list.sh

Output is also formated as a tsv

Parameterize IP allow get ip allow lists (ent and org)

---

gh-cli/README.md

- Updating headings (Adding a `## Scripts` heading and changing subsequent scripts to use `###` instead of `##`
- Updating install instructions (adding windows, linux/other)
- Adding GitHub Actions auth example
- Adding example for updating scopes
- Adding example for authenticating to GitHub Enterprise Server

updating gh-cli readme

---

gh-cli/README.md
gh-cli/get-enterprise-audit-log-for-organization.sh

Adding the enterprise audit log search script
Intended to search for if features have been disabled/enabled (ie: members can delete repos)

Add enterprise audit log

---

gh-cli/README.md
gh-cli/create-enterprise-organization.sh
gh-cli/create-enterprise-organizations-from-list.sh

- parameterizing
- looking up enterprise graphql id based on enterprise name

improving enterprise org creation scripts

---

gh-cli/README.md
gh-cli/add-enterprise-organization-member.sh
gh-cli/get-enterprise-id.sh
gh-cli/get-organization-id.sh
gh-cli/get-user-id.sh
gh-cli/set-organization-membership-for-a-user.sh
gh-cli/update-enterprise-owner-organizational-role.sh

- Parameterizing add member to organization scripts (`./add-enterprise-organization-member.sh` and `./update-enterprise-owner-organizational-role.sh`)
- also parameterizing `get-<enterprise/organization/user>-id.sh` scripts

Parameterizing add member to organization scripts

---

gh-cli/README.md
gh-cli/delete-packages-in-organization.sh
scripts/README.md
scripts/migrate-maven-packages-between-github-instances.sh
scripts/migrate-npm-packages-between-github-instances.sh

`./scripts/migrate-maven-packages-between-github-instances.sh`

Add Maven GitHub Packages migration script

---

gh-cli/README.md
gh-cli/get-organization-migrations-tsv.sh

Gets the list of migrations performed against a given org (using GEI)

get-organization-migrations-tsv

---

gh-cli/add-workflow-file-to-repositories.sh

- pushes a workflow file to specified repos

Add workflow file script

---

gh-cli/add-users-to-team-from-list.sh

This line seems to be duplicated

refactor: remove redundant line

---

gh-cli/get-organization-migrations-tsv.sh

Fix: repositoryName value was not being added to the output

Added header to get-organization-migrations-csv and fix repository name

---

gh-cli/README.md
gh-cli/get-organization-migrations-summary.sh

Prints a summary of GEI migrations by state. Eg (suceeded, failed,queued,....)

get-organization-migrations-summary

---

gh-cli/README.md
gh-cli/get-organization-repositories-by-property.sh

prints the list of repositories in an organization that meet one or more custom properties values.

Add get-organization-repositories-by-property

---

gh-cli/README.md
gh-cli/get-gei-migration-status.sh

- adding script to retrieve information on a GEI migration

adding get-get-migration-status script

---

README.md
gh-cli/README.md

- Fixing blockquote syntax highlighting since old method was deprecated
- see: `https://github.com/orgs/community/discussions/16925`

docs: fixing blockquote highlighing syntax

---

scripts/README.md
scripts/update-codeowners-mappings.js

fix: if codeowners doesn't exist don't try to update it

---

gh-cli/README.md
gh-cli/find-attachments-in-repositories.sh

adding script to loop through issues / pull requests / and optionally issue/pr comments to find attachments

feat: add find attachments script

---

scripts/README.md
scripts/add-dependabot-file-to-repositories.js

adding JavaScript script to add `dependabot.yml` files to a list of repositories

feat: adding dependabot file script

---

gh-cli/README.md
gh-cli/add-user-to-project.sh
gh-cli/get-projects-added-to-repository.sh
gh-cli/get-projects-in-organization.sh

Adding:
- `add-user-to-project.sh`
- `get-projects-added-to-repository.sh`
- `get-projects-in-organization.sh`

feat: add projectsv2 scripts

---

gh-cli/README.md
gh-cli/add-team-to-repository.sh
gh-cli/add-user-to-repository.sh

- add new script for adding a user to a repo
- updating the add team to repo script

Add user and team to repo scripts

---

.github/workflows/lint-readme.yml
scripts/migrate-maven-packages-between-github-instances.sh

- adding fixes from @sparlant (thank you 🙇 !)

fix: fixing maven migration script

---

.github/scripts/lint-readme.js
.github/workflows/lint-readme.yml
scripts/README.md
scripts/ado-workitems-to-github-issues.ps1
scripts/ado_workitems_to_github_issues.ps1

- linting `./scripts/README.md` as well
- fixing any linting errors

feat: lint ./scripts/README.md

---

gh-cli/README.md
gh-cli/download-migration-archive-for-repository.sh
gh-cli/get-enterprise-audit-log-for-organization.sh
gh-cli/get-enterprise-organizations-for-user.sh
gh-cli/get-most-recent-migration-id-for-organization.sh
gh-cli/get-most-recent-migration-id-for-repository.sh
gh-cli/get-organization-migrations-summary.sh
gh-cli/get-organization-migrations-tsv.sh
gh-cli/get-organization-migrations.sh
gh-cli/lock-repository-with-migration.sh
gh-cli/unlock-repository-migration-by-id.sh
gh-cli/unlock-repository-migration.sh

- adding migration scripts for:
- unlocking repo
- locking repo with (mostly) fake export
- downloading archive
- getting migrations for organization

Migration scripts

---

scripts/README.md
scripts/multi-gitter-add-dependabot-file-to-repositories.sh
scripts/multi-gitter-replace-dependabot-file-in-repositories.sh
scripts/multi-gitter-scripts/add-dependabot-file.sh
scripts/multi-gitter-scripts/replace-dependabot-file.sh

adding scripts to be used with [`multi-gitter`](https://github.com/lindell/multi-gitter)

feat: add multi-gitter scripts

---

scripts/README.md
scripts/migrate-docker-containers-between-github-instances.sh

- initial version of the GitHub Container Registry migration script

feat: add docker/container migration script

---

scripts/migrate-npm-packages-between-github-instances.sh

implemented a feature that disregards the case of the source organization's name when replacing it with the target organization's name

Added case insensitivity to package names in migrating npm packages.

---

scripts/migrate-npm-packages-between-github-instances.sh

thanks to @dmtrshpv's [suggestion](https://github.com/joshjohanning/joshjohanning.github.io/issues/38#issuecomment-2022224899)

feat: write failed packages to log and continue

---

scripts/migrate-maven-packages-between-github-instances.sh

Patch code for GitHub to GitHub migrations

---

scripts/migrate-docker-containers-between-github-instances.sh

This fix addresses an issue encountered during the migration of containers between organizations, particularly when the source container name contains a `/` in its path, as seen in the following example:
`ghcr.io/my_org/azure-deploy/nginx:v1`
In such cases, the migration script fails to retrieve the image versions, causing the image to be missed during migration. This update resolves the issue by ensuring the script functions correctly with the revised changes in this commit.

Fix for docker containers nested names migration, where getting failed.

---

gh-cli/README.md
gh-cli/add-team-to-repos-from-list.sh
gh-cli/add-team-to-repositories-from-list.sh

Added a script to add teams along with permissions to repos from a list.

Added add-team-to-repos-from-list script

---

gh-cli/delete-repositories-from-list.sh

'--yes' is not recognized anymore

Replaced flag '--yes' with '--confirm'

---

gh-cli/README.md
gh-cli/get-enterprise-organizations.sh
gh-cli/get-organization-webhooks.sh
gh-cli/get-organizations-apps-count.sh
gh-cli/get-organizations-custom-repository-roles-count.sh
gh-cli/get-organizations-discussions-count.sh
gh-cli/get-organizations-repositories-codeowner-usage.sh
gh-cli/get-organizations-repositories-discussions-count.sh
gh-cli/get-organizations-webhooks-count.sh

fixing from prior PR
- #83
added a few count scripts
renamed codeowner usage script
fixed various bugs/wording

fix!: fix error handling when querying enterprise orgs

---

gh-cli/change-repository-visibility.sh
gh-cli/create-repository-from-template.sh
gh-cli/get-enterprise-members.sh
gh-cli/get-enterprise-owners.sh
gh-cli/get-organizations-projects-count-classic.sh
gh-cli/get-organizations-projects-count.sh
gh-cli/get-organizations-settings.sh
gh-cli/get-saml-identities-in-enterprise.sh
gh-cli/get-saml-identities-in-organization.sh
gh-cli/rename-repository.sh

add hostname
add #!/bin/bash
parameterize inputs

feat: misc improvements

---

gh-cli/copy-permissions-between-organization-repositories.sh

fixes parameter order introduced in #98

fix: correct parameter order for adding collaborators in permission script
